export const TRANSACTION_EDUCATION = {
  txid: "The transaction ID is the double SHA-256 hash of the serialized transaction. It uniquely identifies this transaction, but it is not a wallet or account number.",
  status: "A transaction starts in the mempool and becomes confirmed when a miner includes it in a block.",
  version: "The version tells Bitcoin nodes which transaction-format rules the sender intended to use.",
  locktime: "Locktime can delay when a transaction becomes valid. Zero means there is no transaction-level delay; other values can represent a block height or Unix time.",
  size: "Serialized size is the number of bytes transmitted and stored. Witness data is included.",
  baseSize: "Base size is the transaction size without segregated witness data.",
  witnessSize: "Witness size contains signatures and other SegWit authorization data. It receives a discount when block weight is calculated.",
  weight: "Weight combines base bytes at four units each and witness bytes at one unit each. A block can contain up to four million weight units.",
  vsize: "Virtual size converts weight back into fee-paying bytes: weight divided by four, rounded up.",
  adjustedVsize: "Adjusted virtual size can account for additional policy costs such as signature operations. Miners may use it when evaluating a transaction.",
  sigops: "Signature operations estimate how much cryptographic verification work the scripts require.",
  fee: "The miner fee is total input value minus total output value. It is paid to the miner that confirms the transaction.",
  feeRate: "Fee rate is fee divided by virtual size, measured in satoshis per virtual byte. Miners usually prioritize higher fee rates.",
  effectiveFeeRate: "Effective fee rate may include fees shared through a transaction package, such as parent-and-child fee bumping.",
  totalInput: "Inputs consume previously created, unspent transaction outputs. Their values fund this transaction.",
  totalOutput: "Outputs create new spendable coins. Wallets commonly create one payment output and one change output, but change cannot always be identified reliably.",
  inputs: "Each input points to an earlier unspent output and provides authorization to spend it.",
  outputs: "Each output locks an amount of bitcoin to a script. A future input can spend it by satisfying that script.",
  rbf: "Replace-by-Fee allows an unconfirmed transaction to be replaced by another version paying a higher fee. It is signaled through input sequence numbers.",
  coinbase: "A coinbase transaction is the first transaction in a block. It creates the block subsidy and collects fees, so it has no previous output.",
  prevout: "The previous output, or prevout, is the UTXO consumed by this input.",
  sequence: "Sequence participates in Replace-by-Fee signaling and relative timelocks. 0xffffffff is final; values below 0xfffffffe signal RBF.",
  scriptSig: "ScriptSig is legacy unlocking data placed directly in an input. Native SegWit inputs usually leave it empty.",
  witness: "The witness stack carries signatures and scripts for SegWit inputs. Moving it outside the base transaction fixed transaction malleability and reduced its weight cost.",
  scriptPubKey: "ScriptPubKey is the locking program attached to an output. Spending the output requires data that makes this program succeed.",
  scriptType: "The script type describes the locking template, such as legacy P2PKH, native SegWit, Taproot, or OP_RETURN.",
  address: "An address is a human-friendly encoding of a locking script. Bitcoin itself validates scripts, not account balances.",
  outputValue: "This is the amount locked in the output, measured in satoshis. One bitcoin equals 100,000,000 satoshis.",
  spent: "An output is unspent until another confirmed or mempool transaction references it as an input.",
  blockHeight: "Block height is the position of the confirming block in Bitcoin's chain, starting at the genesis block as height zero.",
  blockHash: "The block hash uniquely identifies the block that confirmed this transaction.",
  blockTime: "Block time is the timestamp declared by the miner. It is approximate and constrained by Bitcoin consensus rules.",
  rawHex: "Raw hexadecimal is the exact serialized transaction exchanged by Bitcoin nodes. Every field, input, output, script, and witness is encoded here.",
} as const;

export type TransactionEducationKey = keyof typeof TRANSACTION_EDUCATION;
