services:
  mempool-matrix:
    build: .
    container_name: mempool-matrix
    restart: unless-stopped
    environment:
      MEMPOOL_API_URL: http://mempool-web/api
    ports:
      - "${TAILSCALE_IP:-100.67.121.90}:${PORT:-3033}:3000"
    mem_limit: 512m
    networks:
      - bitcoin

networks:
  bitcoin:
    external: true
    name: bitcoin-docker_default
